FROM ubuntu:25.10

RUN apt-get update && apt-get install -y \
    git \
    netpbm \
    python3 \
    python3-pip \
    python3-venv \
    make \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

RUN make dev
SHELL ["/bin/bash", "-c"]
CMD ["make", "test"]
