name: Unit tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-24.04
    container:
      image: ubuntu:25.10

    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install -y git netpbm python3-venv make
      - uses: actions/checkout@v4
      - name: Fix git ownership
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Build dev environment
        run: make dev
      - name: Unit tests
        run: make test
